version: '3.8'

services:
  web:
    image: doan1:1.0.0        # Sử dụng image web đã build
    ports:
      - "8080:8080"           # Mở port 8080 cho ứng dụng web
    depends_on:
      - db                    # Đảm bảo db sẽ được khởi động trước
    environment:
      - DB_HOST=db            # Biến môi trường để kết nối tới DB
      - DB_PORT=3306          # Cổng MySQL (nếu sử dụng MySQL)
      - DB_NAME=do_an1        # Tên cơ sở dữ liệu
      - DB_USERNAME=root        # Tên người dùng MySQL
      - DB_PASSWORD=12345     # Mật khẩu MySQL
    networks:
      - doan_network

  db:
    image: database_doan1:1.0.0  # Sử dụng image của database đã build
    environment:
      - MYSQL_ROOT_PASSWORD=12345 # Mật khẩu root MySQL
      - MYSQL_DATABASE=do_an1    # Tên cơ sở dữ liệu ban đầu
    ports:
      - "3307:3306"              # Mở cổng MySQL 3306
    networks:
      - doan_network

networks:
  doan_network:                # Định nghĩa mạng tùy chỉnh cho các container
    driver: bridge