# # Sử dụng hình ảnh Tomcat với JDK 21 và Ubuntu Jammy
# FROM tomcat:10.1.31-jdk21-temurin-jammy

# # Xóa tất cả các ứng dụng mặc định trong thư mục webapps của Tomcat
# RUN rm -rf /usr/local/tomcat/webapps/*

# # Sao chép file WAR vào thư mục webapps của Tomcat
# COPY target/DoAn1-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/

# # Mở cổng 8080 cho Tomcat
# EXPOSE 8080

# # Chạy Tomcat với lệnh mặc định
# CMD ["catalina.sh", "run"]


# Sử dụng official MySQL image
FROM mysql:latest

# Thiết lập mật khẩu root và tên cơ sở dữ liệu mặc định
ENV MYSQL_ROOT_PASSWORD=12345
ENV MYSQL_DATABASE=do_an1

# Copy file data.sql vào thư mục docker-entrypoint-initdb.d
COPY data.sql /docker-entrypoint-initdb.d/

# Cổng MySQL mặc định
EXPOSE 3306